name: credit_score_classification  

channels:
  - defaults
  - conda-forge  

dependencies:
  - python=3.8  
  - scikit-learn==0.24.2
  - joblib==1.1.0
  - catboost==0.26.1
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - xgboost
  - plotly


